DROP TABLE LIGNE_COMMANDE;
DROP TABLE PRODUIT;
DROP TABLE COMMANDE;
DROP TABLE LIVRAISON;
DROP TABLE CLIENT;
DROP TABLE CATEGORIE;
DROP TABLE ADRESSES;

CREATE TABLE ADRESSES (
	IdVille	        NUMBER(6) CONSTRAINT IdVille_PK PRIMARY KEY,
	NomVille	    VARCHAR(30) NOT NULL,
	CpVille	        NUMBER(5) NOT NULL,
	NomRueAdresse	VARCHAR(50) NOT NULL,
	NumeroAdresse	NUMBER(3) NOT NULL,
	SuffixeAdresse	VARCHAR(3)
);

CREATE TABLE CATEGORIE (
	IdCategorie	    NUMBER(6) CONSTRAINT IdCategorie_PK PRIMARY KEY,
	NomCategorie	VARCHAR(20) NOT NULL
);

CREATE TABLE CLIENT (
	IdClient	    NUMBER(6) CONSTRAINT IdClient_PK PRIMARY KEY,
	NomClient	    VARCHAR(20) NOT NULL,
	PrenomClient	VARCHAR(20) NOT NULL,
	EmailClient	    VARCHAR(50) NOT NULL,
	IdVille     	NUMBER(6) CONSTRAINT ClientIdVille_FK REFERENCES ADRESSES
);

CREATE TABLE LIVRAISON (
	IdLivraison	NUMBER(6) CONSTRAINT IdLivraison_PK PRIMARY KEY,
	DateLivraison	Date,
	DureeLivraison	NUMBER(2) NOT NULL,
	IdVille	NUMBER(6) CONSTRAINT LivraisonIdVille_FK REFERENCES ADRESSES
);

CREATE TABLE COMMANDE (
	IdCommande	NUMBER(6) CONSTRAINT IdCommande_PK PRIMARY KEY,
	IdClient	NUMBER(6) CONSTRAINT Commande_IdClient REFERENCES CLIENT,
	DateCommande	DATE NOT NULL,
	StatutCommande	VARCHAR(30) NOT NULL,
	PayementCommande	VARCHAR(20) NOT NULL,
	IdLivraison	NUMBER(6) CONSTRAINT CommandeIdLivraison_FK REFERENCES LIVRAISON
);

CREATE TABLE PRODUIT (
	IdProduit	NUMBER(6) CONSTRAINT IdProduit_PK PRIMARY KEY,
	NomProduit	VARCHAR(20) NOT NULL,
	DescriptionProduit	VARCHAR(40) NOT NULL,
	PrixProduit	DECIMAL(5) NOT NULL,
	StockProduit	NUMBER(3) NOT NULL,
	IdCategorie	NUMBER(6) CONSTRAINT ProduitIdCategorie_FK REFERENCES CATEGORIE
);

CREATE TABLE LIGNE_COMMANDE (
	IdProduit	NUMBER(6) CONSTRAINT LigneCommandeIdProduit_FK REFERENCES PRODUIT,
	IdCommande	NUMBER(6) CONSTRAINT LigneCommandeIdCommande_FK REFERENCES COMMANDE,
	QuantiteCommande	NUMBER(3) NOT NULL,
    PRIMARY KEY (IdProduit, IdCommande)
);